[Workspace]
Home=..\
AppSrcPath=AppSrc
AppHTMLPath=AppHTML
BitmapPath=Bitmaps
IdeSrcPath=IdeSrc
DataPath=Data
DDSrcPath=DDSrc
HelpPath=.
ProgramPath=Programs
FileList=Data\Filelist.cfg
Description=MistralDataflexTest
